### ISSUE TITLE
I don't understand how it works

### ISSUE THREAD

**Issue by IgorN** [richardwilly98/elasticsearch-river-mongodb#165]
I do everything by instruction 
https://github.com/richardwilly98/elasticsearch-river-mongodb

curl -XPUT 'http://localhost:9200/_river/mongodb/_meta' -d '{ 
    "type": "mongodb", 
    "mongodb": { 
        "db": "testmongo", 
        "collection": "person"
    }, 
    "index": {
        "name": "mongoindex", 
        "type": "person" 
    }
}'

than 

use testmongo
var p = {firstName: "John", lastName: "Doe"}
db.person.save(p)

curl -XGET 'http://localhost:9200/testmongo/_search?q=firstName:John'

testmongo - wrong index name, change to mongoindex

curl -XGET 'http://localhost:9200/mongoindex/_search?q=firstName:John'

I see {"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

If i run

http://localhost:9200/_plugin/river-mongodb/ 
I see

mongodb RUNNING
Last Replicated - 
Documents Indexed - 0

Settings:

{
  "index": {
    "name": "mongoindex",
    "type": "person"
  },
  "mongodb": {
    "db": "testmongo",
    "collection": "person"
  },
  "type": "mongodb"
}

Documents Indexed - 0 Whay???
I try to add a lot of document and Alway see 0

If I use

http://localhost:9200/_plugin/head/

I see

_river
size: 5.5kb (5.5kb)
docs: 3 (4)

mongoindex
size: 495b (495b)
docs: 0 (0)

Whay two index and whay docs: 3 (4) and docs: 0 (0)? 

What I do wrang?

Thanks!

**Comment by tianxf305** [comment]
[2015-07-07 17:33:53,159][ERROR][org.elasticsearch.river.mongodb.Slurper] Cannot find oplog.rs collection. Please check this link: http://goo.gl/2x5IW

How to solve the problem。Thank you
