### ISSUE TITLE
Removing document not yet supported

### ISSUE THREAD

**Issue by jeacott** [richardwilly98/elasticsearch-river-mongodb#276]
Hi all,
 can anyone tell me if this river supports mongodb's  update multi  and remove commands?

ref:
http://docs.mongodb.org/manual/reference/method/db.collection.update/#multi-parameter
http://docs.mongodb.org/manual/tutorial/remove-documents

Cheers

**Comment by clslrns** [comment]
`db.users.update({}, {$inc: {'num.followers': 1}}, {multi: true})` worked fine on 3.3M collection.
`db.users.remove({_id: ...})` didn't.

elasticsearch-river-mongodb 2.0.3, MongoDB 2.6, ES 1.3.

**Comment by benmccann** [comment]
We should support removing a document. I'll update this ticket title accordingly. @clslrns if you'd like to send a patch that includes a test that would be much appreciated :-)

**Comment by clslrns** [comment]
I've updated my Elasticsearch and elasticsearch-river-mongodb to 1.4.4 and 2.0.6 correspondingly. And now it works fine. I think this issue can be closed.
