### ISSUE TITLE
count() causes time out during initialization on TokuMX

### ISSUE THREAD

**Issue by badpoet** [richardwilly98/elasticsearch-river-mongodb#397]
Hi,

I'm using ES 1.2.2 and tokumx 1.5.0. The problem is, now, I have a collection with about 50M documents. However, for I'm usign tokumx database, the `Collection.count` operation goes too slow to be finished in minutes.

However, when started, the river count the number of documents before everything begins. The operation goes time-out in about 1 minute. I want to skip the step, or just use an option or something  to customize the time-out. Can you offer an API for me?

Thx

**Comment by badpoet** [comment]
Oh sorry I just forgot this thread.

Actually, since I had commented the relevant lines in the source code and packed codes by myself, the problem was solved.

**Comment by kdkeck** [comment]
I wish you would reopen this issue until a fix is implemented here.  It's great that you're up and running with it now, but this really should be fixed.

**Comment by benmccann** [comment]
Reopening per @kdkeck's request

**Comment by badpoet** [comment]
I'm glad to present my fix here.
[repo](https://github.com/badpoet/elasticsearch-river-mongodb/tree/2.0.1-count-disabled)

I just add modify 2 lines of the code.
1. Disable the counter in the initial import.
2. Disable the verbose "delete" information (importing using scripts leads to many deletions.

Should I pull a request to the project? I don't know if this fix really helps others.
