### ISSUE TITLE
Initial Tutorial is incorrect http://www.matt-reid.co.uk/blog_post.php?id=68#&slider1=4

### ISSUE THREAD

**Issue by dman777** [richardwilly98/elasticsearch-river-mongodb#450]
The initial tutorial, linked in read.me,  http://www.matt-reid.co.uk/blog_post.php?id=68#&slider1=4 is incorrect. 

```javascript
"index":"ES_INDEX_NAME"
``` 

should be:

```javascript
    "index": {
        "name": "mongo_index",
        "type": "config_files"
    }
```

If you don't, there will be errors for can not convert string to something java.map.

**Comment by benmccann** [comment]
Yeah, that's pretty outdated and I wouldn't recommend following that. I updated the README so that hopefully that's clearer now. Thanks https://github.com/richardwilly98/elasticsearch-river-mongodb/commit/cfd52bf5bdbb70325901eebaf7a4bdcd51cdd6b8
