### ISSUE TITLE
The synchronization problem from mongodb to elasticsearch

### ISSUE THREAD

**Issue by huwei2003** [richardwilly98/elasticsearch-river-mongodb#456]
The synchronization problem from mongodb to elasticsearch, because mongodb oplog log is early already did not exist, so the reconstruction of the index in the elasticsearch found that data is not complete, i.e. very earlier data no index, such problems are solved by what method? Thank you

**Comment by huwei2003** [comment]
Who can help me?

**Comment by derEremit** [comment]
I'm not completely sure i understand your english, but the inital import is by default done by importing the collection directly.
After that is done, the river binds to the oplog!
see: skip_initial_import this option will skip the initial import (using collection data) and directly use oplog.rs collection. The default is false.
