### ISSUE TITLE
River for MongoDB 3.0

### ISSUE THREAD

**Issue by dimon222** [richardwilly98/elasticsearch-river-mongodb#477]
I heard MongoDB 3.0 has changes in replication process that may impact on oplog which actually used by elasticseach-river.

Is current latest version of river working with bugs on new mongo or not working at all?
And if it doesn't, is it gonna be hard to get it to work with new version?

**Comment by benmccann** [comment]
Can you put a link here to a description of the replication changes? I haven't investigated this issue specifically yet, but may be able to answer your question if you point to the relevant docs or announcement.

**Comment by jun06t** [comment]
In my environment(ES 1.4.4, Java 1.8.0_31), the latest version of river(v2.0.5) is working on MongoDB 3.0 without errors:-)

**Comment by dimon222** [comment]
Looking at [Compatibility changes MongoDB 3.0](http://docs.mongodb.org/manual/release-notes/3.0-compatibility/)

>**Replica Set Oplog Format Change**  
>MongoDB 3.0 is not compatible with oplog entries generated by versions of MongoDB before 2.2.1. If you upgrade from one of these versions, you must wait for new oplog entries to overwrite all old oplog entries generated by one of these versions before upgrading to 3.0.0 or earlier    

It may mean that it just got rid of compatibility with deprecated format or just was remade with new 3.0 oplog format?!

>Each officially supported driver has release a version that includes support for all new features introduced in MongoDB 3.0. Upgrading to one of these version is strongly recommended as part of the upgrade process.   

So I guess in some cases driver needs to be updated? I don't remember installing driver separately when I was installing river. Either I missed some point or it does update it as part of dependency list ?!  

>MongoDB 3.0 deprecates direct access to system.indexes and system.namespaces collections. Use the createIndexes and listIndexes commands instead.   

As far as I remember river was actually checking system.namespaces collection for whatever reason and wasn't starting till pass this step. I even made a role in MongoDB with permissions for this table for this case.

**Comment by benmccann** [comment]
@dimon222 the one thing we needed to do was update the driver. i've done that. i've also confirmed everything works by running the tests against mongodb 3.0 https://github.com/richardwilly98/elasticsearch-river-mongodb/commit/3a0be4121b29645e2ce2e5b46c206ceeaf879b54

@richardwilly98 do you think we could release a new version of the river that has the new mongodb driver?

**Comment by richardwilly98** [comment]
@benmccann I can release a new version on Monday or Tuesday.

**Comment by dimon222** [comment]
I confirm from my side as well that it works perfectly.

**Comment by benmccann** [comment]
Thanks @richardwilly98 !

**Comment by richardwilly98** [comment]
Release 2.0.6 is available.

**Comment by benmccann** [comment]
Thanks Richard!
