### ISSUE TITLE
Check if an array is empty before indexing a document.

### ISSUE THREAD

**Issue by arunp27** [richardwilly98/elasticsearch-river-mongodb#479]
I've successfully installed MongoDB River. i'm able to auto sync with normal mongodb collection (which doesn't have nested fields) with ES. If comes to nested fields document in a collection i want to check if that field is array or not and also it's length is greater than 0 (Zero) or not. if that array length is zero i'm getting parser error. and also suggest me how to maintain exception handling in river. Thanks in advance.

**Comment by ewgRa** [comment]
1. Try play with direct mapping for this field: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-put-mapping.html

2. Check logs error messages.

**Comment by arunp27** [comment]
Thanks for u'r speedy response @ewgRa. I'm not looking for mapping.. i need to check the field  before it's get indexed into ES. Transform or mongo script filter will work for my scenario...but i'm unable to do transform.

**Comment by ewgRa** [comment]
Maybe this can help you? https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki/MongoDB-custom-filter

**Comment by arunp27** [comment]
@ewgRa, i saw that post already..that will work for 0 or 1 fields, my requirement is different..i need to index the document if a field is an array and also that should not be empty.
i'll give u small example.

{
"business":{
"name": "abc",
"code": 123
},
"social":{
facebook{
"likes":1,
"id":123456
}
}
}

I want to check if social.facebook is empty or not if it is empty then i'll skip that field in indexing.

**Comment by ewgRa** [comment]
@arunp27 seems that "filter" - it is mongodb filter, and it support all that you need, $exists, $type and so on, you just need write right filter.

I check on one my river, for example "filter": "{\"name\": {$exists: false}}" is working well. Try use filter as mongodb filter.

**Comment by arunp27** [comment]
Thanks @ewgRa..it's working fine...i've one more doubt i'm getting some Mapper parser exceptions due to this my indexing is stopping in middle..how to handle this exceptions? pls help me in this regard.

**Comment by ewgRa** [comment]
First answer is - check your logs, there you will find problem, fix it in mongodb and recreate river, cross your finger and hope that it will be succesfull.

Second answer - I'm also have questions about failover in #462, but there is no answer from author, maybe later I will make a pull request for this, but for now this question is open for me also.

**Comment by arunp27** [comment]
ok..Thank u very much...but in my mongodb collection i've a documents with improper schema so i can't fix each field with filters..

**Comment by ewgRa** [comment]
Actually ES is not a real "schema less" on my mind, like MongoDB and if you have very complicated MongoDB documents, I think it is very hard to river it to ElasticSearch, maybe you can play with field mappings and so on, haven't idea. Also there is a question, why all fields needed, try import only what important for search and another information later load from Mongo. Maybe good idea request not a "filter", but "transformer" feature for river, I think it will be usefull option.

**Comment by arunp27** [comment]
Yeah i'm indexing required fields only but those are nested arrays and there schema is not fixed it will varies for some documents..i tried Transform but not working for me..i tried below code.

"transform": [
          {
            "lang": "groovy",
            "script": "if (ctx._source['social']['facebook'].length == 0) ctx._source['social']['facebook'].deleted = true"
          }
        ],

**Comment by ewgRa** [comment]
Ouch, river have this feature, but seems you are definitely use it in wrong way.

ctx it is a "context". ctx._source - can't say where you get it, in wiki there is a ctx.document. And if this is a javascript, you can try "delete ctx.document.social.facebook;" or similar, because this is a javascript. Read manual about "script" carefully and maybe it will be work for you, I haven't expirience with that.

**Comment by arunp27** [comment]
Ok..sure.. Thanks for ur support mate...
