### ISSUE TITLE
Wiki fix

### ISSUE THREAD

**Issue by ewgRa** [richardwilly98/elasticsearch-river-mongodb#488]
Seems that there is some errors in wiki about filters https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki/MongoDB-custom-filter

There is no escaping, also as quotes shows not right. Can wiki be fixed?

Something like this:
```
diff --git a/MongoDB-custom-filter.textile b/MongoDB-custom-filter.textile
index 33db75d..f2e2ca4 100644
--- a/MongoDB-custom-filter.textile
+++ b/MongoDB-custom-filter.textile
@@ -3,7 +3,7 @@ The river settings support a new filter attribute which can be used as a "trigge
 Let"s say there is a document { "name": "richard", "needs_idexing": 0 } stored in MongoDB. This document should be only indexed by ES if needs_indexing is 1. 
 The filter attribute could be used for this scenario. The filter value will be: {"o.needs_indexing": 1}.
 So the river setting will be:
-<pre lang="actionscript">{
+<pre>{
  "type": "mongodb",
  "mongodb": {
   "servers": [
@@ -15,7 +15,7 @@ So the river setting will be:
   "db": "testriver",
   "collection": "documents",
   "gridfs": "false",
-  "filter": "{"o.score" : 1}"
+  "filter": "{\"o.score\" : 1}"
  },
  "index": {
   "name": "documentsindex",
```

Also as maybe remove lang="actionscript" in another places.

**Comment by richardwilly98** [comment]
Done. Let me know if that's better.

I also change the format from textfile to markdown

**Comment by ewgRa** [comment]
Better, but references now broken: 

> fn1. "Dot Notation (Reaching into Objects)":http://www.mongodb.org/display/DOCS/Dot+Notation+(Reaching+into+Objects)

> More details available here [2].
No link

**Comment by ewgRa** [comment]
Also unnecessary comma in custom filter wiki page

"index": {
  "name": "documentsindex",
 }

**Comment by richardwilly98** [comment]
Done.

**Comment by ewgRa** [comment]
Big thanks. Much better
