### ISSUE TITLE
Wiki Troubleshooting change

### ISSUE THREAD

**Issue by ewgRa** [richardwilly98/elasticsearch-river-mongodb#493]
Can you please update https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki#troubleshooting ?

"Add logging in $ES_HOME\config\logging.yml" - point that this file can be in another place, for example in Ubuntu it is /etc/elasticsearch/loggin.yml.

It can be something like this:
"Add logging to your logging.yml file. Usually it can be found at $ES_HOME\config\logging.yml, but this is operation system dependable path. For example in Ubuntu it can be found at /etc/elasticsearch/logging.yml. If you can't find this file, another way is try run 'ps ax | grep elasticsearch | grep -o "path.conf=[^ ]*"' and check path.conf settings."

I'm not native English, if there is errors, please fix it :)

**Comment by benmccann** [comment]
done
