### ISSUE TITLE
Listing more than 10 Rivers

### ISSUE THREAD

**Issue by levofski** [richardwilly98/elasticsearch-river-mongodb#495]
I see that the `/_river/mongodb/list` endpoint is limited to 10 results, however we have more than 10 rivers.

I have checked in https://github.com/richardwilly98/elasticsearch-river-mongodb/blob/master/src/main/java/org/elasticsearch/rest/action/mongodb/RestMongoDBRiverAction.java and I can see that I can send params for the page number and page size, but I cannot work out how.

`http://192.168.20.31:9200/_river/mongodb/list?page=2` returns :-

`{"success":false,"error":"action not found: /_river/mongodb/list?page=2"}`

I have also tried an extended GET :-

`curl -X GET -d '{"page":3}' http://192.168.20.31:9200/_river/mongodb/list`

Please help

**Comment by ewgRa** [comment]
Try curl -XGET -G "http://host:9200/_river/mongodb/list" -d 'page=2'

**Comment by levofski** [comment]
Hi, I tried that command and it returned :- 

`{"success":false,"error":"action not found: /_river/mongodb/list?page=2"}`

**Comment by ewgRa** [comment]
Can you show command and output?

**Comment by levofski** [comment]
Sure, here you go :- 

`root@foolsgold:~# curl -XGET -G "http://192.168.20.31:9200/_river/mongodb/list" -d 'page=2'
{"success":false,"error":"action not found: /_river/mongodb/list?page=2"}
root@foolsgold:~#`

**Comment by levofski** [comment]
This seems to be closer, but still returns the first page :- 

`curl -X GET -d 'page=2' http://192.168.20.31:9200/_river/mongodb/list`

**Comment by ewgRa** [comment]
For me even this work:

 curl -XGET "http://localhost:9200/_river/mongodb/list?page=1"
{"hits":0,"results":[],"count":0,"page":1,"pages":0.0}

Can you try load it from browser? http://localhost:9200/_river/mongodb/list?page=1

Also as which one versions you have? ES, plugins?

**Comment by levofski** [comment]
For me :- 

`http://192.168.20.31:9200/_river/mongodb/list?page=1` returns 

`{"success":false,"error":"action not found: /_river/mongodb/list?page=1"}`

This is on ElasticSearch version 1.2.2 and river plugin version 2.0.1

**Comment by ewgRa** [comment]
I have ES 1.4.2, river - 2.0.6, and it works. Consider ability to upgrade your software.

**Comment by levofski** [comment]
Ok thanks for your time.

**Comment by ewgRa** [comment]
Maybe this help?

https://github.com/richardwilly98/elasticsearch-river-mongodb/blob/elasticsearch-river-mongodb-2.0.1/src/main/java/org/elasticsearch/rest/action/mongodb/RestMongoDBRiverAction.java

Check code for your version, there is different naming of params.

**Comment by levofski** [comment]
Thanks for that, however I am still getting the same errors if I change the param names.

**Comment by ewgRa** [comment]
Another one way, try debug ajax requests, that http://localhost:9200/_plugin/river-mongodb/ make. I don't know about 2.0.1 version, but in 2.0.6 it request list of rivers and allow to navigate between list pages. Try to reproduce this requests. Chrome even can copy it request as curl request.

Good luck! And better to upgrade.
