### ISSUE TITLE
How to create custom index policy?

### ISSUE THREAD

**Issue by droganov** [richardwilly98/elasticsearch-river-mongodb#496]
Hello,
We'de to stream documents collection to elasticsearch, but each document has a counter and counters update frequently. I'd like river to accept any change in document except a counter change, because this creates void server load.

Is there a way/example how to manage this?

**Comment by ewgRa** [comment]
You can use "exclude_fields". Also there is pull request #484 that seems implement your wishes. You can try to test it yourself and support this PR.

**Comment by droganov** [comment]
Thank you!

**Comment by droganov** [comment]
Thank you!

**Comment by ewgRa** [comment]
@droganov please close issue if problem solved
