### ISSUE TITLE
Rivers are going to be deprecated, any thoughts

### ISSUE THREAD

**Issue by derEremit** [richardwilly98/elasticsearch-river-mongodb#508]
https://www.elastic.co/blog/deprecating_rivers

**Comment by ewgRa** [comment]
On my mind kind of strange decision, but maybe it is reasonable, I don't know so much about ES architecture and way that they suggest to use instead of river. It is like Postgresql says that they deprecate replication out of box. Maybe @richardwilly98 will explain with what we can face.

**Comment by benmccann** [comment]
I don't think this will be a big deal. We can still sync from mongo to es. Just as a separate process and not a plugin to es. It probably makes more sense this way actually
