### ISSUE TITLE
Issue while installing elasticsearch-river-mongodb , Please help me

### ISSUE THREAD

**Issue by itsprakashs** [richardwilly98/elasticsearch-river-mongodb#512]
./plugin -install richardwilly98/elasticsearch-river-mongodb/2.0.8

Trying https://github.com/richardwilly98/elasticsearch-river-mongodb/archive/master.zip...
Downloading .................................................................................................................................................................................................................................................................................DONE
Installed richardwilly98/elasticsearch-river-mongodb/2.0.8 into /elastic_soft/elasticsearch-1.4.4/plugins/river-mongodb
Usage:
    -u, --url     [plugin location]   : Set exact URL to download the plugin from
    -i, --install [plugin name]       : Downloads and installs listed plugins [*]
    -t, --timeout [duration]          : Timeout setting: 30s, 1m, 1h... (infinite by default)
    -r, --remove  [plugin name]       : Removes listed plugins
    -l, --list                        : List installed plugins
    -v, --verbose                     : Prints verbose messages
    -s, --silent                      : Run in silent mode
    -h, --help                        : Prints this help message

 [*] Plugin name could be:
     elasticsearch/plugin/version for official elasticsearch plugins (download from download.elasticsearch.org)
     groupId/artifactId/version   for community plugins (download from maven central or oss sonatype)
     username/repository          for site plugins (download from github master)

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

**Comment by richardwilly98** [comment]
Try 2.0.9

**Comment by itsprakashs** [comment]
Thanks for the reply But Sorry getting the Same error with 2.0.9 also

[root@MongoDB-1 bin]# ./plugin -install richardwilly98/elasticsearch-river-mongodb/2.0.9
-> Installing richardwilly98/elasticsearch-river-mongodb/2.0.9...
Downloading ................................................................................................................................................................................................................................................................................DONE

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

**Comment by benmccann** [comment]
Use the command listed in the instructions:

    ./plugin --install com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/2.0.9

**Comment by itsprakashs** [comment]
Thanks a lot.....it worked.
