### ISSUE TITLE
Unable to Connect to Remote Elastic Search using Pentaho Data integration

### ISSUE THREAD

**Issue by itsprakashs** [richardwilly98/elasticsearch-river-mongodb#522]
Guys Please let me know  ...Is there any work around.

Server : Elastic Search 1.4.4

Client machine : PDI 5.3

I could able to connect to Mongodb successfully using PDI but the same is not working with Elastic search.

**Comment by benmccann** [comment]
This is a bug tracker for ElasticSearch MongoDB River. Not a help forum for Pentaho Data Integration. Unless you've found a bug in the code of the river, this is the wrong place for such an issue.
