### ISSUE TITLE
Compatibility with ES 1.7.2

### ISSUE THREAD

**Issue by focusme** [richardwilly98/elasticsearch-river-mongodb#551]
Is the river plugin compatible with Elasticsearch version 1.7.2?
I use "mvn eclipse:eclipse"
have more errors :+1: 
D:\work\es\elasticsearch-river-mongodb-2.0.10>mvn eclipse:eclipse
[INFO] Scanning for projects...
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or on
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch-river-mongodb 2.0.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or on
[INFO]
[INFO] >>> maven-eclipse-plugin:2.10:eclipse (default-cli) > generate-resources @ elasticsearch-river-mongodb >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ elasticsearch-river-mongodb ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.2:create (default) @ elasticsearch-river-mongodb ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: D:\work\es\elasticsearch-river-mongodb-2.0.10
[INFO] Storing buildNumber: null at timestamp: 1439782407652
[INFO] Executing: cmd.exe /X /C "git rev-parse --verify HEAD"
[INFO] Working directory: D:\work\es\elasticsearch-river-mongodb-2.0.10
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- build-helper-maven-plugin:1.5:add-source (add-source) @ elasticsearch-river-mongodb ---
[INFO] Source directory: D:\work\es\elasticsearch-river-mongodb-2.0.10\src\main\groovy added.
[INFO]
[INFO] --- build-helper-maven-plugin:1.5:add-resource (add-resource) @ elasticsearch-river-mongodb ---
[INFO]
[INFO] <<< maven-eclipse-plugin:2.10:eclipse (default-cli) < generate-resources @ elasticsearch-river-mongodb <<<
[INFO]
[INFO] --- maven-eclipse-plugin:2.10:eclipse (default-cli) @ elasticsearch-river-mongodb ---
[INFO] Using Eclipse Workspace: D:\work\es
[INFO] Adding default classpath container: org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/Jav
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.144 s
[INFO] Finished at: 2015-08-17T11:33:29+08:00
[INFO] Final Memory: 26M/461M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse (default-cli) on project elasticsearch-river-mongodb:
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by RdrgPorto** [comment]
River Plugin is not compatible with 1.7.2. If you want to test River, you will need a Elasticsearch 1.4.2.
You can see this plugin https://github.com/phutchins/logstash-input-mongodb.
Also there is another plugin: https://github.com/elastic/packetbeat
Cheers

**Comment by focusme** [comment]
thank you very much.
