### ISSUE TITLE
Question: can't install mongodb river plugin on windows command

### ISSUE THREAD

**Issue by shenxianpeng** [richardwilly98/elasticsearch-river-mongodb#591]
I'm tring  install mongo river plugin using `bin/plugin --install com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/2.0.9` command

C:\elasticsearch-5.2.2>bin/plugin --install com.github.richardwilly98.elasticsearch/elasticsearch-river-mongodb/2.0.9
'bin' is not recognized as an internal or external command,
operable program or batch file.

could someone tell me what's the problem? Thanks in advance!

**Comment by dpasch01** [comment]
The windows version uses elasticsearch-plugin.bat, so to use it from the command line type:
$ bin/elasticsearch-plugin install <plugin>
